name: Setup ZMK dependencies
description: Pull in ZMK and Zephyr modules

inputs:
  config:
    description: "Config or tests path relative to repo root"
    type: string
    required: false
    default: "config"

  always-update-west:
    description: "Update west modules on cache hit"
    type: boolean
    required: false

outputs:
  workspace:
    description: "Path to build environment"
    value: ${{ steps.workspace.outputs.workspace }}

  zmk-src-dir:
    description: "Path to zmk/app if detected"
    value: ${{ steps.export.outputs.zmk-src-dir }}

runs:
  using: composite
  steps:
    - name: Move config to temporary isolated workspace
      id: workspace
      shell: bash
      run: |
        # Necessary for repos that are themselves Zephyr modules but doesn't hurt in general
        workspace="${RUNNER_TEMP}/tests" && echo "workspace=${workspace}" >> $GITHUB_OUTPUT
        mkdir -p "${workspace}/${{ inputs.config }}"
        cp -R ${{ inputs.config }}/* "${workspace}/${{ inputs.config }}/"

    - name: Cache west modules
      id: cache-west
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.workspace.outputs.workspace }}/modules/
          ${{ steps.workspace.outputs.workspace }}/tools/
          ${{ steps.workspace.outputs.workspace }}/zephyr/
          ${{ steps.workspace.outputs.workspace }}/bootloader/
          ${{ steps.workspace.outputs.workspace }}/zmk/

        key: zephyr-${{ hashFiles(format('{0}/west.yml', inputs.config)) }}
        restore-keys: zephyr-

    - name: Initialize west workspace
      working-directory: ${{ steps.workspace.outputs.workspace }}
      shell: bash
      run: |
        west init -l "${{ inputs.config }}"
        if [ ${{ steps.cache-west.outputs.cache-hit != 'true' || inputs.always-update-west }} == true ]; then
          west update --fetch-opt=--filter=tree:0
        fi
        west zephyr-export

    - name: Find ZMK source directory
      id: export
      working-directory: ${{ steps.workspace.outputs.workspace }}
      shell: bash
      run: |
        echo "zmk-src-dir=$(find -path '*/zmk/app/west.yml' -printf '%h\n' -quit)" >> $GITHUB_OUTPUT
