name: Build ZMK firmware (nix)
on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - build.yaml

jobs:
  build:
    uses: urob/zmk-actions/.github/workflows/build-user-config.yml@v3
    with:
      # Use 'gnuarmemb' for best performance or 'zephyr' for maximum compatibility.
      toolchain: zephyr
