name: Run module tests

on:
  workflow_call:
    inputs:
      test-dir:
        description: "Path to the tests directory"
        type: string
        required: false
        default: "tests"
      verbose:
        description: "Show detailed build logs"
        type: boolean
        required: false
      always-update-west:
        description: "Run west update on cache hits"
        type: boolean
        required: false

jobs:
  run-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up ZMK workspace
        uses: urob/zmk-actions/setup@v2
        id: setup
        with:
          config: ${{ inputs.test-dir }}
          always-update-west: ${{ inputs.always-update-west }}

      - name: Test
        id: test
        uses: urob/zmk-actions/test@v2
        with:
          verbose: ${{ inputs.verbose }}
          test-dir: ${{ inputs.test-dir }}
          workspace: ${{ steps.setup.outputs.workspace }}
          zmk-src-dir: ${{ steps.setup.outputs.zmk-src-dir }}
