name: Create a new module release
on:
  workflow_call:
    inputs:
      release_branch:
        description: "Branch to create the release from"
        default: "main"
        required: false
        type: string

jobs:
  bump-version:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'Bump ZMK')
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump version and push tag
        run: |
          tag=$(echo ${{ github.event.pull_request.title }} | sed -n 's/^.*\(v[^[:space:]]*\).*/\1/p')
          echo "tag=${tag}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -f $tag
          git tag -f ${tag%.*}
          if [ ${tag%.*.*} != "v0" ]; then
            git tag -f ${tag%.*.*}
          fi
          git push -f --tags origin ${{ github.ref_name }}:${{ inputs.release_branch }}
