name: Check for new ZMK releases

on:
  workflow_call:
    inputs:
      upstream:
        description: "Upstream repository to track"
        default: "zmkfirmware/zmk"
        required: false
        type: string
      west_path:
        description: "Path to the west.yml file"
        default: "tests/west.yml"
        required: false
        type: string
      pr_branch:
        description: "Branch to push the PR to"
        default: "upgrade-zmk"
        required: false
        type: string
      pr_label:
        description: "Label to add to the PR"
        default: ""
        required: false
        type: string

permissions:
  contents: write

jobs:
  upgrade-zmk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest ZMK release
        run: |
          ZMK_VERSION=$(curl -s https://api.github.com/repos/${{ inputs.upstream }}/releases/latest | jq -r '.tag_name')
          echo "ZMK_VERSION=${ZMK_VERSION}" >> $GITHUB_ENV

      - name: Upgrade test dependencies
        run: |
          yq e -i '(.manifest.projects[] | select(.name=="zmk") | .revision) = env(ZMK_VERSION)' ${{ inputs.west_path }}

      - name: Detect changes
        id: changes
        run:
          echo "count=$(git status --porcelain=v1 2>/dev/null | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit & push changes
        if: steps.changes.outputs.count > 0
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -a -m "Bump ZMK to ${ZMK_VERSION}"
          git push -f origin ${{ github.ref_name }}:${{ inputs.pr_branch }}

      - name: Open pull request if needed
        if: steps.changes.outputs.count > 0
        run: |
          echo "${{ secrets.ZMK_MODULES_ACTIONS }}" | gh auth login --with-token
          # Only open a new PR if the branch is not attached to an existing one. Needs a PAT with read access to
          # metadata, and read & write acess to actions and pull requests.
          PR=$(gh pr list --head ${{ inputs.pr_branch }} --json number -q '.[0].number')
          if [ -z $PR ]; then
            pr_label=${{ inputs.pr_label }}
            gh pr create --head ${{ inputs.pr_branch }} --title "Bump ZMK to ${ZMK_VERSION}" ${pr_label:+--label "$pr_label"} \
              --body "Full log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          else
            echo "Pull request already exists, won't create a new one."
          fi
